export const predefinedTags = [
    "Java Exceptions",
    "Python Errors",
    "JavaScript Bugs",
    "C++ Segmentation Fault",
    "Null Pointer Exception",
    "Memory Leaks",
    "Syntax Errors",
    "Threading Issues",
    "Concurrency Problems",
    "TypeErrors",
    "Stack Overflow",
    "Infinite Loops",
    "Dependency Issues",
    "Library Conflicts",
    "API Errors",
    "Database Connection Issues",
    "Runtime Errors",
    "File Handling Errors",
    "Array Index Out Of Bounds",
    "Performance Optimization",
    "Compilation Issues",
    "Garbage Collection",
    "Deadlocks",
    "Out Of Memory Error"
];

